### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by m1guelpf** [rodericktech/laracon-online-2018-notes#1]
I'm creating a recopilation of all 2018 Laracon notes (Online, US, EU & AU), and I would love to use yours (crediting you as the author, of course), but for that I need you to either add a license to this repo (MIT or Unlicense) or to give me explicit permission.

**Comment by rodericktech** [comment]
I have now added an MIT license to this repo - feel free to use the notes as long as you credit the source.  Thanks for asking!
